copyright = "krak-pol"
baseURL = "http://example.org/"
languageCode = "de-ge"
title = "Mario Construcciones"
theme = "i18n_and_gallery"

DefaultContentLanguage = "de"
defaultContentLanguageInSubdir = true
[languages]
  [languages.de]
    contentDir = 'content/deutsh'
    title = "Mario Gebäude"
    languageName = "Deutsch"
    weight = 1
    [languages.de.menu]
      [[languages.de.menu.main]]
        name = "Haus"
        pre = "home"
        url = "/"
        weight = 1
        [[languages.de.menu.main]]
          name = "Portfolio"
          pre = "layers"
          url = "/portfolio/"
          weight = 2
        [[languages.de.menu.main]]
          name = "Kontact"
          pre = "pen-tool"
          url = "/contact/"
          weight = 3
        [[languages.de.menu.main]]
          name = "Etikett"
          pre = "tag"
          url = "/tags/"
          weight = 4

  [languages.es]
    contentDir = 'content/spanish'
    title = "Mario Construcciones"
    languageName = "Español"
    weight = 2

    [languages.es.menu]
      [[languages.es.menu.main]]
        name = "Casa"
        pre = "home"
        url = "/"
        weight = 1
        [[languages.es.menu.main]]
          name = "Carpeta"
          pre = "layers"
          url = "/portfolio/"
          weight = 2
        [[languages.es.menu.main]]
          name = "Contacto"
          pre = "pen-tool"
          url = "/contact/"
          weight = 3
        [[languages.es.menu.main]]
          name = "Etiqueta"
          pre = "tag"
          url = "/tags/"
          weight = 4
