name = "I18n_and_gallery"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "This theme is intended to suport i18n translations and gallery."
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Kornel Labun"
  homepage = "kornellabun.com"
